from string import *
print(ascii_letters)
print("*"*20)
print(ascii_lowercase)
print('*'*20)
print(ascii_uppercase)
print('*'*20)
print(digits)
print('*'*20)
print(octdigits)
print('*'*20)
print(hexdigits)
print('*'*20)
print(printable)
print('*'*20)
print(punctuation)
print("*"*20)
print(whitespace)
print('*'*20)
print(capwords('hey kunal 123joshi '))
print('*'*20)
print("hey kunal 123joshi".title())
print('*'*20)
print("hey kunal 123joshi".capitalize())
